# Generated by Django 5.1.6 on 2025-02-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ismingiz')),
                ('email', models.EmailField(max_length=254, verbose_name='elektron pochta')),
                ('number', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Erkak'), ('F', 'Ayol')], default='Erkak')),
                ('message', models.TextField(verbose_name='xabar')),
            ],
        ),
    ]
